### ISSUE TITLE
Error when used with Laravel Breeze package

### ISSUE THREAD

**Issue by Mutahhar** [AkrilliA/laravel-beyond#90] opened 2023-02-21 20:30 UTC
I managed to use this package with **Laravel version 10** and **Laravel Breeze**.

I setup the package with following command `php artisan beyond:setup --skip-delete`.

Laravel breeze has created few routes in `routes\auth.php` file. The controllers for those routes are single action controllers, having only `__invoke` method. So when I run `composer dump-autoload` command it gives the error below. **@AkrilliA** Please help, thanks 👍.

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   UnexpectedValueException

  Invalid route action: [App\Http\Controllers\Auth\EmailVerificationPromptController].

  at D:\laragon\www\TrueRewardsLaravel\vendor\laravel\framework\src\Illuminate\Routing\RouteAction.php:92
     88▕      */
     89▕     protected static function makeInvokable($action)
     90▕     {
     91▕         if (! method_exists($action, '__invoke')) {
  ➜  92▕             throw new UnexpectedValueException("Invalid route action: [{$action}].");
     93▕         }
     94▕
     95▕         return $action.'@__invoke';
     96▕     }

  i   `App\Http\Controllers\Auth\EmailVerificationPromptController` was not found: Controller class `App\Http\Controllers\Auth\EmailVerificationPromptController` for one of your routes was not found. Are you sure this controller exists and is imported correctly?

  1   D:\laragon\www\TrueRewardsLaravel\vendor\laravel\framework\src\Illuminate\Routing\RouteAction.php:47
      Illuminate\Routing\RouteAction::makeInvokable("App\Http\Controllers\Auth\EmailVerificationPromptController")

  2   D:\laragon\www\TrueRewardsLaravel\vendor\laravel\framework\src\Illuminate\Routing\Route.php:191
      Illuminate\Routing\RouteAction::parse("verify-email", ["App\Http\Controllers\Auth\EmailVerificationPromptController", "App\Http\Controllers\Auth\EmailVerificationPromptController"])
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by regnerisch** [comment] 2023-02-22 08:12
Could you tell me in which order you executed the commands? Recommendation is to install alle required packages, after that run `php artisan beyond:setup (--skip-delete)` and run `composer dump-autoload`. 

As we manipulate the directory structure of Laravel we facing lot of issues with 3. party packages which need the default directory structure. 

We currently working on a better solution to fully support 3. party packages.

**Comment by Mutahhar** [comment] 2023-02-22 10:48
Thank you @regnerisch for your response. 
I am acatually using Laravel Breeze with InertiaJS. 
Here is the order in which I executed the commands.

I first installed `Laravel 10` and `Breeze` by running this command.
`laravel new FolderName --pest --breeze`

Then configured `InertiaJs`.

Then executed the following commands to install and setup `laravel-beyond`.

1. `composer require --dev akrillia/laravel-beyond`
2. `php artisan beyond:setup --skip-delete`
3. Put following code in the `boot` method of  `AppServiceProvider`
```
\Illuminate\Database\Eloquent\Factories\Factory::guessFactoryNamesUsing(function (string $modelName) {
    return '\Database\Factories\\' . class_basename($modelName) . 'Factory';
});
```

Then I tried to run `composer dump-autoload` but it gave the error mentioned in my previous comment.

**Comment by alexgaal** [comment] 2023-02-22 10:52
I assume that this route is registered through Breeze, did you try to overwrite the route?

```
Route::get($url, [EmailVerificationPromptController::class, '__invoke');
```

should help you fix this problem with the current version of Laravel Beyond. As @regnerisch mentioned we are currently working on a better solution which will be released within the next major release.

**Comment by Mutahhar** [comment] 2023-02-22 11:16
Thankyou @alexgaal for your response. 
I did not overwrite the route. I will look into that. 

I think the issue was due to **invokable controllers**. I tried to create another custom invokable controller outside of `laravel breeze` but faced the same issue.

I can see that the invokable controllers are part of laravel since laravel 5.6 https://laravel.com/docs/5.6/controllers#single-action-controllers.

So I think it should be working with this pacakge.

**Comment by alexgaal** [comment] 2023-02-22 11:21
I'd appreciate if you could try to overwrite the route and test it with an invokable controller. They should work perfectly fine as soon as the issue is fixed.

**Comment by alexgaal** [comment] 2023-02-22 11:22
I'll test if invokable controllers are an issue we should cover. Thanks for letting me know. Feel free to reopen the issue when overwriting didn't fix your problem.

**Closed by alexgaal** 2023-02-22 11:22 UTC

**Comment by Mutahhar** [comment] 2023-02-23 10:26
> did you try to overwrite the route?
> 
> ```
> Route::get($url, [EmailVerificationPromptController::class, '__invoke');
> ```

Hi @alexgaal.
I tried with overwriting the route and yes it did work 🤩. Thankyou very much 👍.
Waiting for your next release which will fix this 🙂.

**Comment by regnerisch** [comment] 2023-03-19 10:08
We just released v7.0.0-beta.1. Using it is on your own risk. Also be aware that it works complete different. But it fixes any problems with third party packages (if used inside a new project without the changed directory structure of older Laravel Beyond versions)

**Comment by Mutahhar** [comment] 2023-03-27 12:45
@regnerisch Oh great 👍
In the meantime, I started to structure my app as per the **Laravel Beyond Crud** course without any package. But I will definitely check your new version. 
Thanks 🙂

**Comment by alexgaal** [comment] 2023-03-27 12:56
We'll provide an Upgrade Guide as soon as we get into a stable state. Feel free to support us on this 😌
